steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dataanalysis-image', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud', 'run', 'deploy', 'dataanalysis-service',
      '--image', 'gcr.io/$PROJECT_ID/dataanalysis-image',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/dataanalysis-image'

options:
  logging: CLOUD_LOGGING_ONLY